export type * from "./types";
export {
  DEFAULT_RISK_POLICY,
  MIN_CANDLES_BY_TIMEFRAME,
  STALE_MS_BY_TIMEFRAME,
} from "./types";
export {
  type ExposureSnapshot,
  type RiskDecision,
  computeLongExposure,
  evaluateOrderRisk,
} from "./risk";
export {
  aggregateTimeframeObservations,
  filterUsableTimeframeObservations,
} from "./temporal";
export {
  applyPaperFill,
  computePerformance,
  updatePositionMarketPrices,
  type PaperFillDecision,
} from "./paper";
export {
  applyFillToCycles,
  summarizeClosedCycles,
  type LifecycleResult,
} from "./lifecycle";
export {
  canAcceptProposal,
  emptyProposalGuardState,
  markProposalAccepted,
  proposalGuardKey,
  type ProposalGuardState,
} from "./proposal-guard";
export {
  demoInstrumentId,
  parseInstrumentId,
  toInstrumentId,
} from "./instrument";
export {
  applySlippage,
  computeFee,
  isValidPrice,
  isValidQuantity,
} from "./validate";
export { deriveSessionState, sessionToFlyState } from "./session";
export { clamp01, toDOMRectLike } from "./math";
export {
  DEFAULT_CALIBRATION_CONFIG,
  DEFAULT_CALIBRATION_PROFILE,
  BUNDLED_GLOBAL_PRESET,
  BUNDLED_GLOBAL_PRESET_VERSION,
  FORBIDDEN_CONTRIBUTION_KEYS,
  GLOBAL_PRESET_SCHEMA_VERSION,
  applyCalibration,
  applyGlobalPreset,
  assertAnonymousObservationSafe,
  attachChecksum,
  brokerCategoryFromBrokerId,
  buildGlobalPresetCandidate,
  comparePresetVersions,
  computeCalibration,
  holdingDurationBucket,
  observationFromBrain,
  observationToSample,
  resetCalibration,
  scoreCalibration,
  sha256Hex,
  validateGlobalPreset,
  verifyPresetChecksum,
  type AnonymousPaperObservation,
  type CalibrationConfig,
  type CalibrationProfile,
  type CalibrationSample,
  type GlobalCalibrationPreset,
  type GlobalPresetGates,
  type LearningObservation,
} from "./calibration";
export {
  computeExtendedPerformance,
  computePerformanceByBrainMode,
  filterClosedCycles,
  type BrainModePerformance,
  type ExtendedPerformance,
  type PerformanceRange,
} from "./performance-analytics";
export {
  DEFAULT_LEARNING_PIPELINE_CONFIG,
  OUTCOME_HORIZON_MS,
  assertRealNeuronIds,
  computeFutureOutcome,
  brainOutputFromModular,
  evaluateModularMock,
  horizonToMs,
  registerConnectomeNeuronIds,
  shouldEvaluateBrain,
  shouldUploadSummary,
  validateModuleDefinitions,
  type ChartModuleOutput,
  type DecisionModuleOutput,
  type FutureOutcomeRecord,
  type LearningPipelineConfig,
  type MarketObservationRecord,
  type ModularEvaluateResult,
  type ModuleId,
  type ModuleOutputRecord,
  type NeuralModuleDefinition,
  type OutcomeHorizon,
  type PendingOutcomeRecord,
  type RiskModuleOutput,
  type ScannerModuleOutput,
  type VolumeModuleOutput,
} from "./modular";
export {
  DEFAULT_SYMBOL_SEEDS,
  EXPLORATION_TIMEFRAMES,
  MAX_CANDIDATES,
  PAPER_GATES,
  appendActivityLog,
  calculateTrendConflict,
  canProposePaperTrade,
  computeInterestScore,
  computeMarketFeatures,
  computeNovelty,
  decideIntent,
  emptyFlyMemory,
  featuresToMarketSlice,
  formatLogLine,
  motionForState,
  nextTimeframe,
  observedTimeframes,
  rankCandidates,
  recentlyVisitedPenalty,
  recordObservation,
  recordVisit,
  selectSymbol,
  stepExploration,
  thoughtFor,
  type AgentState,
  type ExplorationEvent,
  type ExplorationMotion,
  type ExplorationSpeed,
  type ExplorationState,
  type ExplorerResult,
  type FlyIntent,
  type FlyMemory,
  type HudSnapshot,
  type MarketFeatures,
  type OhlcvBar,
  type PolicyResult,
  type SymbolCandidate,
} from "./exploration";
